### ISSUE TITLE
GPlayerLeaveMatchEvent exception caused by NPE

### ISSUE THREAD

**Issue by Europia79** [PaintballWarEdition/BattleGadgets-Issues#1]
Wasn't sure if this error is an actual issue or a non-issue: (because one of the players isn't real, it's a VirtualPlayer used for testing).

http://hastebin.com/vapumopake.tex

it appears that SpotMarker::stopMarking() receives a null argument.

**Comment by blablubbabc** [comment]
Seems like Bukkit.getPlayer(uuid) returns null for your virtual player at match end / when the player leaves the match. Not sure how VirtualPlayers work in detail, but is this something which could be fixed in VirtualPlayers?
Either way, I have slightly changed the affected class to workaround this, which is possible because I have a cached player instance at this place anyways.
However at other places in code this might not be the case.. so might be good to modify VirtualPlayers to better match bukkit's behavior in this case nevertheless.. if that is possible..
